Redis
paulrozhkin/hand-control-mqtt pull request #21
Opened 2020-11-14 17:54 UTC by mishkamashka

2020-11-15 10:01 UTC, paulrozhkin commented
На текущий момент уже [определены](https://github.com/paulrozhkin/handcontrol-documentation/tree/master/proto) и [описаны](https://github.com/paulrozhkin/handcontrol-documentation/blob/master/api.md) все сущности, которые есть на протезе, а не только настройки. Требуется дополнить redis dao для соответствия им.

2020-11-15 10:05 UTC, paulrozhkin requested changes

2020-11-15 10:05 UTC, paulrozhkin commented on server/src/main/kotlin/com/handcontrol/server/entity/Settings.kt
> +class Settings (
На текущий момент уже [определены](https://github.com/paulrozhkin/handcontrol-documentation/tree/master/proto) и [описаны](https://github.com/paulrozhkin/handcontrol-documentation/blob/master/api.md) все сущности, которые есть на протезе, а не только настройки. Требуется дополнить redis dao для соответствия им.

2020-11-15 10:05 UTC, paulrozhkin commented on server/src/main/kotlin/com/handcontrol/server/entity/Prothesis.kt
> +        val settings: Settings //todo: check if settings load from redis by getProthesis
Так оно проверено или нет? Если да, то убрать коммент. Если нет, то проверить.

2020-11-29 17:36 UTC, nbiryulin reviewed
Не вижу
setOffline()
isOnline()
changeProthesis()

2020-12-06 11:15 UTC, nbiryulin commented on server/src/main/kotlin/com/handcontrol/server/entity/Prothesis.kt
> +        val settings: Settings //todo: check if settings load from redis by getProthesis
https://github.com/paulrozhkin/hand-control-mqtt/issues/29

Вынес в отдельный тикет дабы уже замержить

2020-12-06 11:22 UTC, nbiryulin commented
Merged with tech debts: https://github.com/paulrozhkin/hand-control-mqtt/issues/30 , https://github.com/paulrozhkin/hand-control-mqtt/issues/29

2020-12-06 11:22 UTC, merged